version: "3"

services:
  apis:
    container_name: dev_svs_apis
    volumes:
      - ./APIs/src:/app/src
  audit:
    container_name: dev_svs_audit
    volumes:
      - ./Audit/src:/app/src
  postgres:
    container_name: dev_svs_postgres
    # Below to save the database in the current directory
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"