version: "3"

services:
  apis:
    container_name: prod_svs_apis
    build: 
      dockerfile: prod.Dockerfile
      args:
        # This is the IP address of the server, which the docker container will be running on
        - BASE_IP=143.117.69.4
    ports:
      - "48800:8000"
  audit:
    container_name: prod_svs_audit
    build: 
      dockerfile: prod.Dockerfile
      # overwrites the environment variable within teh '.env', if adding more the Dockerfile needs to be updated
      args:
        - REACT_APP_API_URL=http://143.117.69.4:48801
    ports:
      # The ports cannot be the same as the fist docker-compose file
      - "48300:80"    
  postgres:
    container_name: prod_svs_postgres
    ports:
      - "48545:5432"