version: "3"

services:
  apis:
    container_name: dev_svs_apis
    volumes:
      - ./APIs/src:/app/src
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  audit:
    container_name: dev_svs_audit
    volumes:
      - ./Audit/src:/app/src
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  postgres:
    container_name: dev_svs_postgres
    # Uncomment below to save the database in the current directory
    # volumes:
      # - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: dev_svs_pgadmin4_container
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./pgadmin4/pgpass:/pgadmin4/pgpass # passwords for the connections in this file, must be in the format hostname:port:database:username:password
    ports:
      - "5050:80"
    depends_on:
      - "postgres"