version: "3"

services:
  apis:
    container_name: prod_svs_apis
    build: 
      dockerfile: prod.Dockerfile
    ports:
      - "48800:8000"
  audit:
    container_name: prod_svs_audit
    build: 
      dockerfile: prod.Dockerfile
      # overwrites the environment variable within teh '.env', if adding more the Dockerfile needs to be updated
      args:
        - REACT_APP_API_URL=http://localhost:48800
    ports:
      # The ports cannot be the same as the fist docker-compose file
      - "48300:80"    
  postgres:
    container_name: prod_svs_postgres
    ports:
      - 5432:48543