version: "3"

volumes:
  svs-data: 

services:
  apis:
    container_name: svs_apis
    build:
      context: ./APIs
      dockerfile: Dockerfile
  audit:
    container_name: svs_audit
    build: 
      context: ./Audit
      dockerfile: Dockerfile
  postgres:
    container_name: svs_postgres
    # latest version is 16, need to change this to 16
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - svs-data:/var/lib/postgresql

      # mounts the sql files to be used within the start up shell script
      - ./sql:/sql

      # Runs *.sh or *.sql when first creating the database, if the database already exists, the files do not execute
      # read more [here](https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f)
      - ./database-set-up.sh:/docker-entrypoint-initdb.d/database-set-up.sh # the shell script is required to create the tables within the correct database